import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1780064644484 implements MigrationInterface {
    name = 'Migration1780064644484'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "extension_devices" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128) NOT NULL, "device_token" varchar(512), "browser" varchar(100), "version" varchar(20), "connection_status" varchar(20), "last_error" text, "last_seen" datetime, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_b2391557a1a780d5fd64682f81c" UNIQUE ("device_id"))`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" varchar PRIMARY KEY NOT NULL, "qr_code_id" varchar NOT NULL, "user_id" varchar NOT NULL, "adapter_used" varchar(50) NOT NULL, "amount" decimal(15,2) NOT NULL, "status" text NOT NULL DEFAULT ('PENDING'), "bank_end2end_id" varchar(100), "provider_payment_id" varchar(100), "provider_status" varchar(50), "last_polled_at" datetime, "bank_response" text, "account_label" varchar(100), "config_snapshot" text, "error_message" text, "retry_count" integer NOT NULL DEFAULT (0), "executed_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_97f2b5c8deb08739881119c115" UNIQUE ("qr_code_id"))`);
        await queryRunner.query(`CREATE TABLE "qr_codes" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128), "payload" text NOT NULL, "payload_hash" varchar(64) NOT NULL, "amount" decimal(15,2), "merchant_name" varchar(255), "merchant_city" varchar(100), "pix_key" varchar(255), "transaction_id" varchar(100), "source_url" text, "status" text NOT NULL DEFAULT ('PENDING'), "can_pay" boolean NOT NULL DEFAULT (1), "is_raw" boolean NOT NULL DEFAULT (0), "captured_at" datetime NOT NULL, "approved_at" datetime, "approved_by" varchar(36), "institution_name" varchar(255), "asaas_status" varchar(50), "expiration_date" datetime, "payment_config_snapshot" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fdc8e9ddbfac8bc10b85c40579b" UNIQUE ("payload_hash"))`);
        await queryRunner.query(`CREATE TABLE "bank_accounts" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "provider" varchar(50) NOT NULL, "label" varchar(255), "encrypted_credentials" text NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('ACTIVE'), "is_default" boolean NOT NULL DEFAULT (0), "environment" varchar(10), "last_sync_error" text, "last_sync_at" datetime, "last_balance_check_at" datetime, "last_known_balance" decimal(15,2), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_e92f9e4f03453050041e4f85f9" ON "bank_accounts" ("user_id", "provider") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bacb970de306f5acc6a06223c3" ON "bank_accounts" ("user_id", "is_default") WHERE "is_default" IS TRUE`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "email" varchar(255) NOT NULL, "password_hash" varchar(255), "api_key" varchar(64) NOT NULL, "api_key_rotated_at" datetime, "role" varchar(20) NOT NULL DEFAULT ('USER'), "features" text, "subscription_expires_at" datetime, "current_session_id" varchar(64), "password_reset_token" varchar(128), "password_reset_expires_at" datetime, "bank_adapter" varchar(50) NOT NULL DEFAULT ('mock'), "bank_config" text, "is_active" boolean NOT NULL DEFAULT (1), "last_login_at" datetime, "last_login_ip" varchar(64), "last_login_ua" varchar(255), "extension_last_version" varchar(50) NOT NULL DEFAULT ('1.0.0'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_16bfa631de67a4fafe7ce3f2fed" UNIQUE ("api_key"))`);
        await queryRunner.query(`CREATE TABLE "raw_qr_captures" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128), "rawContent" text NOT NULL, "raw_hash" varchar(64) NOT NULL, "source_url" text, "page_title" varchar(255), "capture_method" varchar(50), "status" varchar(50) NOT NULL DEFAULT ('capturado_bruto'), "validation_status" varchar(50) NOT NULL DEFAULT ('pending_validation'), "can_pay" boolean NOT NULL DEFAULT (0), "captured_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "payment_webhooks" ("id" varchar PRIMARY KEY NOT NULL, "source" varchar(50) NOT NULL, "event_id" varchar(255), "event_type" varchar(100), "payment_id" varchar(36), "raw_body" text NOT NULL, "parsed_body" text, "ip_address" varchar(255), "signature" varchar(255), "signature_valid" boolean NOT NULL DEFAULT (0), "status" varchar(20) NOT NULL DEFAULT ('RECEIVED'), "error_message" text, "processing_time_ms" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b64e3375e2ce7392c24ed632c" ON "payment_webhooks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcfbf7e2e64b466888b6ec07aa" ON "payment_webhooks" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8800885a7266c7d34a9ca9f258" ON "payment_webhooks" ("source", "event_id") `);
        await queryRunner.query(`CREATE TABLE "financial_receipts" ("id" varchar PRIMARY KEY NOT NULL, "payment_id" varchar NOT NULL, "bank_end2end_id" varchar(100), "type" varchar(50) NOT NULL DEFAULT ('BANK_PROVIDED'), "format" varchar(20), "receipt_url" text, "receipt_data" text, "parsed_data" text, "original_filename" text, "file_size_bytes" integer, "mime_type" text, "content_hash" varchar(64), "emitted_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4b839e9b089690be2f46ac0b2" ON "financial_receipts" ("bank_end2end_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b83b233fd219d4b7c9e9eed69" ON "financial_receipts" ("payment_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "entity" varchar(50) NOT NULL, "entity_id" varchar(36) NOT NULL, "action" varchar(100) NOT NULL, "actor_id" varchar(36), "old_data" text, "new_data" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "temporary_extension_devices" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128) NOT NULL, "device_token" varchar(512), "browser" varchar(100), "version" varchar(20), "connection_status" varchar(20), "last_error" text, "last_seen" datetime, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_b2391557a1a780d5fd64682f81c" UNIQUE ("device_id"), CONSTRAINT "FK_8996f2c38e62ab6e858114edde8" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_extension_devices"("id", "user_id", "device_id", "device_token", "browser", "version", "connection_status", "last_error", "last_seen", "is_active", "created_at", "updated_at") SELECT "id", "user_id", "device_id", "device_token", "browser", "version", "connection_status", "last_error", "last_seen", "is_active", "created_at", "updated_at" FROM "extension_devices"`);
        await queryRunner.query(`DROP TABLE "extension_devices"`);
        await queryRunner.query(`ALTER TABLE "temporary_extension_devices" RENAME TO "extension_devices"`);
        await queryRunner.query(`CREATE TABLE "temporary_payments" ("id" varchar PRIMARY KEY NOT NULL, "qr_code_id" varchar NOT NULL, "user_id" varchar NOT NULL, "adapter_used" varchar(50) NOT NULL, "amount" decimal(15,2) NOT NULL, "status" text NOT NULL DEFAULT ('PENDING'), "bank_end2end_id" varchar(100), "provider_payment_id" varchar(100), "provider_status" varchar(50), "last_polled_at" datetime, "bank_response" text, "account_label" varchar(100), "config_snapshot" text, "error_message" text, "retry_count" integer NOT NULL DEFAULT (0), "executed_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_97f2b5c8deb08739881119c115" UNIQUE ("qr_code_id"), CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_97f2b5c8deb08739881119c1151" FOREIGN KEY ("qr_code_id") REFERENCES "qr_codes" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_payments"("id", "qr_code_id", "user_id", "adapter_used", "amount", "status", "bank_end2end_id", "provider_payment_id", "provider_status", "last_polled_at", "bank_response", "account_label", "config_snapshot", "error_message", "retry_count", "executed_at", "created_at") SELECT "id", "qr_code_id", "user_id", "adapter_used", "amount", "status", "bank_end2end_id", "provider_payment_id", "provider_status", "last_polled_at", "bank_response", "account_label", "config_snapshot", "error_message", "retry_count", "executed_at", "created_at" FROM "payments"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`ALTER TABLE "temporary_payments" RENAME TO "payments"`);
        await queryRunner.query(`CREATE TABLE "temporary_qr_codes" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128), "payload" text NOT NULL, "payload_hash" varchar(64) NOT NULL, "amount" decimal(15,2), "merchant_name" varchar(255), "merchant_city" varchar(100), "pix_key" varchar(255), "transaction_id" varchar(100), "source_url" text, "status" text NOT NULL DEFAULT ('PENDING'), "can_pay" boolean NOT NULL DEFAULT (1), "is_raw" boolean NOT NULL DEFAULT (0), "captured_at" datetime NOT NULL, "approved_at" datetime, "approved_by" varchar(36), "institution_name" varchar(255), "asaas_status" varchar(50), "expiration_date" datetime, "payment_config_snapshot" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fdc8e9ddbfac8bc10b85c40579b" UNIQUE ("payload_hash"), CONSTRAINT "FK_f1f441f26cb73a38ee7026ab35c" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a0c8fc6fb65b4ce6596d44e5368" FOREIGN KEY ("device_id") REFERENCES "extension_devices" ("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_qr_codes"("id", "user_id", "device_id", "payload", "payload_hash", "amount", "merchant_name", "merchant_city", "pix_key", "transaction_id", "source_url", "status", "can_pay", "is_raw", "captured_at", "approved_at", "approved_by", "institution_name", "asaas_status", "expiration_date", "payment_config_snapshot", "created_at") SELECT "id", "user_id", "device_id", "payload", "payload_hash", "amount", "merchant_name", "merchant_city", "pix_key", "transaction_id", "source_url", "status", "can_pay", "is_raw", "captured_at", "approved_at", "approved_by", "institution_name", "asaas_status", "expiration_date", "payment_config_snapshot", "created_at" FROM "qr_codes"`);
        await queryRunner.query(`DROP TABLE "qr_codes"`);
        await queryRunner.query(`ALTER TABLE "temporary_qr_codes" RENAME TO "qr_codes"`);
        await queryRunner.query(`DROP INDEX "IDX_e92f9e4f03453050041e4f85f9"`);
        await queryRunner.query(`DROP INDEX "IDX_bacb970de306f5acc6a06223c3"`);
        await queryRunner.query(`CREATE TABLE "temporary_bank_accounts" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "provider" varchar(50) NOT NULL, "label" varchar(255), "encrypted_credentials" text NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('ACTIVE'), "is_default" boolean NOT NULL DEFAULT (0), "environment" varchar(10), "last_sync_error" text, "last_sync_at" datetime, "last_balance_check_at" datetime, "last_known_balance" decimal(15,2), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_29146c4a8026c77c712e01d922b" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_bank_accounts"("id", "user_id", "provider", "label", "encrypted_credentials", "status", "is_default", "environment", "last_sync_error", "last_sync_at", "last_balance_check_at", "last_known_balance", "created_at", "updated_at") SELECT "id", "user_id", "provider", "label", "encrypted_credentials", "status", "is_default", "environment", "last_sync_error", "last_sync_at", "last_balance_check_at", "last_known_balance", "created_at", "updated_at" FROM "bank_accounts"`);
        await queryRunner.query(`DROP TABLE "bank_accounts"`);
        await queryRunner.query(`ALTER TABLE "temporary_bank_accounts" RENAME TO "bank_accounts"`);
        await queryRunner.query(`CREATE INDEX "IDX_e92f9e4f03453050041e4f85f9" ON "bank_accounts" ("user_id", "provider") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bacb970de306f5acc6a06223c3" ON "bank_accounts" ("user_id", "is_default") WHERE "is_default" IS TRUE`);
        await queryRunner.query(`CREATE TABLE "temporary_raw_qr_captures" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128), "rawContent" text NOT NULL, "raw_hash" varchar(64) NOT NULL, "source_url" text, "page_title" varchar(255), "capture_method" varchar(50), "status" varchar(50) NOT NULL DEFAULT ('capturado_bruto'), "validation_status" varchar(50) NOT NULL DEFAULT ('pending_validation'), "can_pay" boolean NOT NULL DEFAULT (0), "captured_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_a37bd886bb13db6cbc331471947" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_70510f3697e606563b56f60c849" FOREIGN KEY ("device_id") REFERENCES "extension_devices" ("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_raw_qr_captures"("id", "user_id", "device_id", "rawContent", "raw_hash", "source_url", "page_title", "capture_method", "status", "validation_status", "can_pay", "captured_at", "created_at") SELECT "id", "user_id", "device_id", "rawContent", "raw_hash", "source_url", "page_title", "capture_method", "status", "validation_status", "can_pay", "captured_at", "created_at" FROM "raw_qr_captures"`);
        await queryRunner.query(`DROP TABLE "raw_qr_captures"`);
        await queryRunner.query(`ALTER TABLE "temporary_raw_qr_captures" RENAME TO "raw_qr_captures"`);
        await queryRunner.query(`DROP INDEX "IDX_c4b839e9b089690be2f46ac0b2"`);
        await queryRunner.query(`DROP INDEX "IDX_9b83b233fd219d4b7c9e9eed69"`);
        await queryRunner.query(`CREATE TABLE "temporary_financial_receipts" ("id" varchar PRIMARY KEY NOT NULL, "payment_id" varchar NOT NULL, "bank_end2end_id" varchar(100), "type" varchar(50) NOT NULL DEFAULT ('BANK_PROVIDED'), "format" varchar(20), "receipt_url" text, "receipt_data" text, "parsed_data" text, "original_filename" text, "file_size_bytes" integer, "mime_type" text, "content_hash" varchar(64), "emitted_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_9b83b233fd219d4b7c9e9eed699" FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_financial_receipts"("id", "payment_id", "bank_end2end_id", "type", "format", "receipt_url", "receipt_data", "parsed_data", "original_filename", "file_size_bytes", "mime_type", "content_hash", "emitted_at", "created_at") SELECT "id", "payment_id", "bank_end2end_id", "type", "format", "receipt_url", "receipt_data", "parsed_data", "original_filename", "file_size_bytes", "mime_type", "content_hash", "emitted_at", "created_at" FROM "financial_receipts"`);
        await queryRunner.query(`DROP TABLE "financial_receipts"`);
        await queryRunner.query(`ALTER TABLE "temporary_financial_receipts" RENAME TO "financial_receipts"`);
        await queryRunner.query(`CREATE INDEX "IDX_c4b839e9b089690be2f46ac0b2" ON "financial_receipts" ("bank_end2end_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b83b233fd219d4b7c9e9eed69" ON "financial_receipts" ("payment_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_9b83b233fd219d4b7c9e9eed69"`);
        await queryRunner.query(`DROP INDEX "IDX_c4b839e9b089690be2f46ac0b2"`);
        await queryRunner.query(`ALTER TABLE "financial_receipts" RENAME TO "temporary_financial_receipts"`);
        await queryRunner.query(`CREATE TABLE "financial_receipts" ("id" varchar PRIMARY KEY NOT NULL, "payment_id" varchar NOT NULL, "bank_end2end_id" varchar(100), "type" varchar(50) NOT NULL DEFAULT ('BANK_PROVIDED'), "format" varchar(20), "receipt_url" text, "receipt_data" text, "parsed_data" text, "original_filename" text, "file_size_bytes" integer, "mime_type" text, "content_hash" varchar(64), "emitted_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "financial_receipts"("id", "payment_id", "bank_end2end_id", "type", "format", "receipt_url", "receipt_data", "parsed_data", "original_filename", "file_size_bytes", "mime_type", "content_hash", "emitted_at", "created_at") SELECT "id", "payment_id", "bank_end2end_id", "type", "format", "receipt_url", "receipt_data", "parsed_data", "original_filename", "file_size_bytes", "mime_type", "content_hash", "emitted_at", "created_at" FROM "temporary_financial_receipts"`);
        await queryRunner.query(`DROP TABLE "temporary_financial_receipts"`);
        await queryRunner.query(`CREATE INDEX "IDX_9b83b233fd219d4b7c9e9eed69" ON "financial_receipts" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4b839e9b089690be2f46ac0b2" ON "financial_receipts" ("bank_end2end_id") `);
        await queryRunner.query(`ALTER TABLE "raw_qr_captures" RENAME TO "temporary_raw_qr_captures"`);
        await queryRunner.query(`CREATE TABLE "raw_qr_captures" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128), "rawContent" text NOT NULL, "raw_hash" varchar(64) NOT NULL, "source_url" text, "page_title" varchar(255), "capture_method" varchar(50), "status" varchar(50) NOT NULL DEFAULT ('capturado_bruto'), "validation_status" varchar(50) NOT NULL DEFAULT ('pending_validation'), "can_pay" boolean NOT NULL DEFAULT (0), "captured_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "raw_qr_captures"("id", "user_id", "device_id", "rawContent", "raw_hash", "source_url", "page_title", "capture_method", "status", "validation_status", "can_pay", "captured_at", "created_at") SELECT "id", "user_id", "device_id", "rawContent", "raw_hash", "source_url", "page_title", "capture_method", "status", "validation_status", "can_pay", "captured_at", "created_at" FROM "temporary_raw_qr_captures"`);
        await queryRunner.query(`DROP TABLE "temporary_raw_qr_captures"`);
        await queryRunner.query(`DROP INDEX "IDX_bacb970de306f5acc6a06223c3"`);
        await queryRunner.query(`DROP INDEX "IDX_e92f9e4f03453050041e4f85f9"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" RENAME TO "temporary_bank_accounts"`);
        await queryRunner.query(`CREATE TABLE "bank_accounts" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "provider" varchar(50) NOT NULL, "label" varchar(255), "encrypted_credentials" text NOT NULL, "status" varchar(20) NOT NULL DEFAULT ('ACTIVE'), "is_default" boolean NOT NULL DEFAULT (0), "environment" varchar(10), "last_sync_error" text, "last_sync_at" datetime, "last_balance_check_at" datetime, "last_known_balance" decimal(15,2), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "bank_accounts"("id", "user_id", "provider", "label", "encrypted_credentials", "status", "is_default", "environment", "last_sync_error", "last_sync_at", "last_balance_check_at", "last_known_balance", "created_at", "updated_at") SELECT "id", "user_id", "provider", "label", "encrypted_credentials", "status", "is_default", "environment", "last_sync_error", "last_sync_at", "last_balance_check_at", "last_known_balance", "created_at", "updated_at" FROM "temporary_bank_accounts"`);
        await queryRunner.query(`DROP TABLE "temporary_bank_accounts"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bacb970de306f5acc6a06223c3" ON "bank_accounts" ("user_id", "is_default") WHERE "is_default" IS TRUE`);
        await queryRunner.query(`CREATE INDEX "IDX_e92f9e4f03453050041e4f85f9" ON "bank_accounts" ("user_id", "provider") `);
        await queryRunner.query(`ALTER TABLE "qr_codes" RENAME TO "temporary_qr_codes"`);
        await queryRunner.query(`CREATE TABLE "qr_codes" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128), "payload" text NOT NULL, "payload_hash" varchar(64) NOT NULL, "amount" decimal(15,2), "merchant_name" varchar(255), "merchant_city" varchar(100), "pix_key" varchar(255), "transaction_id" varchar(100), "source_url" text, "status" text NOT NULL DEFAULT ('PENDING'), "can_pay" boolean NOT NULL DEFAULT (1), "is_raw" boolean NOT NULL DEFAULT (0), "captured_at" datetime NOT NULL, "approved_at" datetime, "approved_by" varchar(36), "institution_name" varchar(255), "asaas_status" varchar(50), "expiration_date" datetime, "payment_config_snapshot" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fdc8e9ddbfac8bc10b85c40579b" UNIQUE ("payload_hash"))`);
        await queryRunner.query(`INSERT INTO "qr_codes"("id", "user_id", "device_id", "payload", "payload_hash", "amount", "merchant_name", "merchant_city", "pix_key", "transaction_id", "source_url", "status", "can_pay", "is_raw", "captured_at", "approved_at", "approved_by", "institution_name", "asaas_status", "expiration_date", "payment_config_snapshot", "created_at") SELECT "id", "user_id", "device_id", "payload", "payload_hash", "amount", "merchant_name", "merchant_city", "pix_key", "transaction_id", "source_url", "status", "can_pay", "is_raw", "captured_at", "approved_at", "approved_by", "institution_name", "asaas_status", "expiration_date", "payment_config_snapshot", "created_at" FROM "temporary_qr_codes"`);
        await queryRunner.query(`DROP TABLE "temporary_qr_codes"`);
        await queryRunner.query(`ALTER TABLE "payments" RENAME TO "temporary_payments"`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" varchar PRIMARY KEY NOT NULL, "qr_code_id" varchar NOT NULL, "user_id" varchar NOT NULL, "adapter_used" varchar(50) NOT NULL, "amount" decimal(15,2) NOT NULL, "status" text NOT NULL DEFAULT ('PENDING'), "bank_end2end_id" varchar(100), "provider_payment_id" varchar(100), "provider_status" varchar(50), "last_polled_at" datetime, "bank_response" text, "account_label" varchar(100), "config_snapshot" text, "error_message" text, "retry_count" integer NOT NULL DEFAULT (0), "executed_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "REL_97f2b5c8deb08739881119c115" UNIQUE ("qr_code_id"))`);
        await queryRunner.query(`INSERT INTO "payments"("id", "qr_code_id", "user_id", "adapter_used", "amount", "status", "bank_end2end_id", "provider_payment_id", "provider_status", "last_polled_at", "bank_response", "account_label", "config_snapshot", "error_message", "retry_count", "executed_at", "created_at") SELECT "id", "qr_code_id", "user_id", "adapter_used", "amount", "status", "bank_end2end_id", "provider_payment_id", "provider_status", "last_polled_at", "bank_response", "account_label", "config_snapshot", "error_message", "retry_count", "executed_at", "created_at" FROM "temporary_payments"`);
        await queryRunner.query(`DROP TABLE "temporary_payments"`);
        await queryRunner.query(`ALTER TABLE "extension_devices" RENAME TO "temporary_extension_devices"`);
        await queryRunner.query(`CREATE TABLE "extension_devices" ("id" varchar PRIMARY KEY NOT NULL, "user_id" varchar NOT NULL, "device_id" varchar(128) NOT NULL, "device_token" varchar(512), "browser" varchar(100), "version" varchar(20), "connection_status" varchar(20), "last_error" text, "last_seen" datetime, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_b2391557a1a780d5fd64682f81c" UNIQUE ("device_id"))`);
        await queryRunner.query(`INSERT INTO "extension_devices"("id", "user_id", "device_id", "device_token", "browser", "version", "connection_status", "last_error", "last_seen", "is_active", "created_at", "updated_at") SELECT "id", "user_id", "device_id", "device_token", "browser", "version", "connection_status", "last_error", "last_seen", "is_active", "created_at", "updated_at" FROM "temporary_extension_devices"`);
        await queryRunner.query(`DROP TABLE "temporary_extension_devices"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_9b83b233fd219d4b7c9e9eed69"`);
        await queryRunner.query(`DROP INDEX "IDX_c4b839e9b089690be2f46ac0b2"`);
        await queryRunner.query(`DROP TABLE "financial_receipts"`);
        await queryRunner.query(`DROP INDEX "IDX_8800885a7266c7d34a9ca9f258"`);
        await queryRunner.query(`DROP INDEX "IDX_bcfbf7e2e64b466888b6ec07aa"`);
        await queryRunner.query(`DROP INDEX "IDX_5b64e3375e2ce7392c24ed632c"`);
        await queryRunner.query(`DROP TABLE "payment_webhooks"`);
        await queryRunner.query(`DROP TABLE "raw_qr_captures"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "IDX_bacb970de306f5acc6a06223c3"`);
        await queryRunner.query(`DROP INDEX "IDX_e92f9e4f03453050041e4f85f9"`);
        await queryRunner.query(`DROP TABLE "bank_accounts"`);
        await queryRunner.query(`DROP TABLE "qr_codes"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TABLE "extension_devices"`);
    }

}
